### ISSUE TITLE
Undefined but requested input: mqtt_consumer/Compilation Error : unknown field ‘Timeout’

### ISSUE THREAD

**Issue by Vivien-Michel** [influxdata/telegraf#702]
I use the .deb version (0.10.2) on a Ubuntu 14.04 on the AWS platform. And I can't find how "activate" this plugin. I didn't find the directory where the plugins are or the line command to use it.
I tried to compile with go(1.5.3, the last one on the website) as in the tutorial but I have this error : 
github.com/influxdata/influxdb/client/v2
$GOPATH/src/github.com/influxdata/influxdb/client/v2/client.go:122:4: error: unknown field ‘Timeout’ in ‘http.Client’
    Timeout:   conf.Timeout,

Have you already use the mqtt_consumer or get this type of error during the compilation?
Best regards

**Comment by sparrc** [comment]
that plugin is currently only in master, it will be available in 0.10.3 (see https://github.com/influxdata/telegraf/blob/master/CHANGELOG.md)
