### ISSUE TITLE
Telegraf compilation error

### ISSUE THREAD

**Issue by sporokh** [influxdata/telegraf#931]
Hello guys, trying to compile telegraf from the source regarding this manual:
```
From Source:

Telegraf manages dependencies via gdm, which gets installed via the Makefile if you don't have it already. You also must build with golang version 1.5+.

1. Install Go
2. Setup your GOPATH
3. Run go get github.com/influxdata/telegraf
4. Run cd $GOPATH/src/github.com/influxdata/telegraf
5. Run make
```

But when I run make, i got this error:
```
go get github.com/sparrc/gdm
gdm restore
======= Go Dependency Manager =======
= working dir: /golang/src/github.com/influxdata/telegraf
= GOPATH:      /golang
=====================================
> Restoring /golang/src/git.eclipse.org/gitroot/paho/org.eclipse.paho.mqtt.golang.git to 617c801af238c3af2d9e72c5d4a0f02edad03ce5
> Restoring /golang/src/github.com/Shopify/sarama to 8aadb476e66ca998f2f6bb3c993e9a2daa3666b9
> Restoring /golang/src/github.com/Sirupsen/logrus to 219c8cb75c258c552e999735be6df753ffc7afdc
> Restoring /golang/src/github.com/amir/raidman to 53c1b967405155bfc8758557863bf2e14f814687
> Restoring /golang/src/github.com/aws/aws-sdk-go to 13a12060f716145019378a10e2806c174356b857
> Restoring /golang/src/github.com/beorn7/perks to 3ac7bf7a47d159a033b107610db8a1b6575507a4
> Restoring /golang/src/github.com/cenkalti/backoff to 4dc77674aceaabba2c7e3da25d4c823edfb73f99
> Restoring /golang/src/github.com/couchbase/go-couchbase to cb664315a324d87d19c879d9cc67fda6be8c2ac1
> Restoring /golang/src/github.com/couchbase/gomemcached to a5ea6356f648fec6ab89add00edd09151455b4b2
> Restoring /golang/src/github.com/couchbase/goutils to 5823a0cbaaa9008406021dc5daf80125ea30bba6
> Restoring /golang/src/github.com/dancannon/gorethink to e7cac92ea2bc52638791a021f212145acfedb1fc
> Restoring /golang/src/github.com/davecgh/go-spew to 5215b55f46b2b919f50a1df0eaa5886afe4e3b3d
> Restoring /golang/src/github.com/eapache/go-resiliency to b86b1ec0dd4209a588dc1285cdd471e73525c0b3
> Restoring /golang/src/github.com/eapache/queue to ded5959c0d4e360646dc9e9908cff48666781367
> Restoring /golang/src/github.com/fsouza/go-dockerclient to a49c8269a6899cae30da1f8a4b82e0ce945f9967
> Restoring /golang/src/github.com/go-sql-driver/mysql to 1fca743146605a172a266e1654e01e5cd5669bee
> Restoring /golang/src/github.com/golang/protobuf to 552c7b9542c194800fd493123b3798ef0a832032
> Restoring /golang/src/github.com/golang/snappy to 427fb6fc07997f43afa32f35e850833760e489a7
> Restoring /golang/src/github.com/gonuts/go-shellquote to e842a11b24c6abfb3dd27af69a17f482e4b483c2
> Restoring /golang/src/github.com/gorilla/context to 1ea25387ff6f684839d82767c1733ff4d4d15d0a
> Restoring /golang/src/github.com/gorilla/mux to c9e326e2bdec29039a3761c07bece13133863e1e
> Restoring /golang/src/github.com/hailocab/go-hostpool to e80d13ce29ede4452c43dea11e79b9bc8a15b478
> Restoring /golang/src/github.com/influxdata/config to b79f6829346b8d6e78ba73544b1e1038f1f1c9da
> Restoring /golang/src/github.com/influxdata/influxdb to e3fef5593c21644f2b43af55d6e17e70910b0e48
> Restoring /golang/src/github.com/influxdata/toml to af4df43894b16e3fd2b788d01bd27ad0776ef2d0
> Restoring /golang/src/github.com/klauspost/crc32 to 19b0b332c9e4516a6370a0456e6182c3b5036720
> Restoring /golang/src/github.com/lib/pq to e182dc4027e2ded4b19396d638610f2653295f36
> Restoring /golang/src/github.com/matttproud/golang_protobuf_extensions to d0c3fe89de86839aecf2e0579c40ba3bb336a453
> Restoring /golang/src/github.com/miekg/dns to cce6c130cdb92c752850880fd285bea1d64439dd
> Restoring /golang/src/github.com/mreiferson/go-snappystream to 028eae7ab5c4c9e2d1cb4c4ca1e53259bbe7e504
> Restoring /golang/src/github.com/naoina/go-stringutil to 6b638e95a32d0c1131db0e7fe83775cbea4a0d0b
> Restoring /golang/src/github.com/nats-io/nats to b13fc9d12b0b123ebc374e6b808c6228ae4234a3
> Restoring /golang/src/github.com/nats-io/nuid to 4f84f5f3b2786224e336af2e13dba0a0a80b76fa
> Restoring /golang/src/github.com/nsqio/go-nsq to 0b80d6f05e15ca1930e0c5e1d540ed627e299980
> Restoring /golang/src/github.com/prometheus/client_golang to 18acf9993a863f4c4b40612e19cdd243e7c86831
> Restoring /golang/src/github.com/prometheus/client_model to fa8ad6fec33561be4280a8f0514318c79d7f6cb6
> Restoring /golang/src/github.com/prometheus/common to e8eabff8812b05acf522b45fdcd725a785188e37
> Restoring /golang/src/github.com/prometheus/procfs to 406e5b7bfd8201a36e2bb5f7bdae0b03380c2ce8
> Restoring /golang/src/github.com/samuel/go-zookeeper to 218e9c81c0dd8b3b18172b2bbfad92cc7d6db55f
> Restoring /golang/src/github.com/shirou/gopsutil to 1f32ce1bb380845be7f5d174ac641a2c592c0c42
> Restoring /golang/src/github.com/soniah/gosnmp to b1b4f885b12c5dcbd021c5cee1c904110de6db7d
> Restoring /golang/src/github.com/streadway/amqp to b4f3ceab0337f013208d31348b578d83c0064744
> Restoring /golang/src/github.com/stretchr/testify to 1f4a1643a57e798696635ea4c126e9127adb7d3c
> Restoring /golang/src/github.com/wvanbergen/kafka to 1a8639a45164fcc245d5c7b4bd3ccfbd1a0ffbf3
> Restoring /golang/src/github.com/wvanbergen/kazoo-go to 0f768712ae6f76454f987c3356177e138df258f8
> Restoring /golang/src/github.com/zensqlmonitor/go-mssqldb to ffe5510c6fa5e15e6d983210ab501c815b56b363
> Restoring /golang/src/golang.org/x/crypto to 5dc8cb4b8a8eb076cbb5a06bc3b8682c15bdbbd3
> Restoring /golang/src/golang.org/x/net to 6acef71eb69611914f7a30939ea9f6e194c78172
> Restoring /golang/src/golang.org/x/text to a71fd10341b064c10f4a81ceac72bcf70f26ea34
> Restoring /golang/src/gopkg.in/dancannon/gorethink.v1 to 7d1af5be49cb5ecc7b177bf387d232050299d6ef
> Restoring /golang/src/gopkg.in/fatih/pool.v2 to cba550ebf9bce999a02e963296d4bc7a486cb715
> Restoring /golang/src/gopkg.in/mgo.v2 to d90005c5262a3463800497ea5a89aed5fe22c886
> Restoring /golang/src/gopkg.in/yaml.v2 to a83829b6f1293c91addabc89d0571c246397bbf4
go install -ldflags "-X main.Version=0.11.1-52-g474d6db" ./...
# github.com/couchbase/go-couchbase/platform
/tmp/go-build125032724/github.com/couchbase/go-couchbase/platform/_obj/platform.cgo2.c:23:19: fatal error: errno.h: No such file or directory
compilation terminated.
Makefile:17: recipe for target 'build' failed
make: *** [build] Error 2
```

Spec:
`GNU Make 4.1`
`go version go1.6 linux/amd64`

Could you help me with this?

**Comment by sparrc** [comment]
You might try building with CGO_ENABLED=0. Not sure why you don't have a CGO compatible system, are you using alpine linux?

**Comment by sporokh** [comment]
@sparrc yes, I am using alpine-linux.
I've managed to build it with `make container-for-docker`. That was the solution I actually needed.

**Comment by xiwangren** [comment]
hi ,
1. Install Go
2. Setup your GOPATH
3. Run go get github.com/influxdata/telegraf
4. Run cd $GOPATH/src/github.com/influxdata/telegraf
5. Run make
when make , cmd hang ，not return back :(

go get github.com/sparrc/gdm
gdm restore
======= Go Dependency Manager =======
= working dir: /home/figure/working/go/src/github.com/influxdata/telegraf
= GOPATH:      /home/figure/working/go
=====================================
> Restoring /home/figure/working/go/src/collectd.org to 2ce144541b8903101fb8f1483cc0497a68798122
> Restoring /home/figure/working/go/src/github.com/aerospike/aerospike-client-go to 95e1ad7791bdbca44707fedbb29be42024900d9c
> Restoring /home/figure/working/go/src/github.com/amir/raidman to c74861fe6a7bb8ede0a010ce4485bdbb4fc4c985
> Restoring /home/figure/working/go/src/github.com/apache/thrift to 4aaa92ece8503a6da9bc6701604f69acf2b99d07
> Restoring /home/figure/working/go/src/github.com/aws/aws-sdk-go to c861d27d0304a79f727e9a8a4e2ac1e74602fdc0
> Restoring /home/figure/working/go/src/github.com/beorn7/perks to 4c0e84591b9aa9e6dcfdf3e020114cd81f89d5f9
> Restoring /home/figure/working/go/src/github.com/bsm/sarama-cluster to ccdc0803695fbce22f1706d04ded46cd518fd832
> Restoring /home/figure/working/go/src/github.com/cenkalti/backoff to b02f2bbce11d7ea6b97f282ef1771b0fe2f65ef3
> Restoring /home/figure/working/go/src/github.com/couchbase/go-couchbase to bfe555a140d53dc1adf390f1a1d4b0fd4ceadb28
> Restoring /home/figure/working/go/src/github.com/couchbase/gomemcached to 4a25d2f4e1dea9ea7dd76dfd943407abf9b07d29
> Restoring /home/figure/working/go/src/github.com/couchbase/goutils to 5823a0cbaaa9008406021dc5daf80125ea30bba6
> Restoring /home/figure/working/go/src/github.com/davecgh/go-spew to 346938d642f2ec3594ed81d874461961cd0faa76
> Restoring /home/figure/working/go/src/github.com/docker/docker to f5ec1e2936dcbe7b5001c2b817188b095c700c27
> Restoring /home/figure/working/go/src/github.com/docker/go-connections to 990a1a1a70b0da4c4cb70e117971a4f0babfbf1a
> Restoring /home/figure/working/go/src/github.com/eapache/go-resiliency to b86b1ec0dd4209a588dc1285cdd471e73525c0b3
> Restoring /home/figure/working/go/src/github.com/eapache/go-xerial-snappy to bb955e01b9346ac19dc29eb16586c90ded99a98c
> Restoring /home/figure/working/go/src/github.com/eapache/queue to 44cc805cf13205b55f69e14bcb69867d1ae92f98
> Restoring /home/figure/working/go/src/github.com/eclipse/paho.mqtt.golang to d4f545eb108a2d19f9b1a735689dbfb719bc21fb
> Restoring /home/figure/working/go/src/github.com/go-logfmt/logfmt to 390ab7935ee28ec6b286364bba9b4dd6410cb3d5
> Restoring /home/figure/working/go/src/github.com/go-sql-driver/mysql to 2e00b5cd70399450106cec6431c2e2ce3cae5034
> Restoring /home/figure/working/go/src/github.com/gobwas/glob to bea32b9cd2d6f55753d94a28e959b13f0244797a
> Restoring /home/figure/working/go/src/github.com/go-ini/ini to 9144852efba7c4daf409943ee90767da62d55438
> Restoring /home/figure/working/go/src/github.com/gogo/protobuf to 7b6c6391c4ff245962047fc1e2c6e08b1cdfa0e8
> Restoring /home/figure/working/go/src/github.com/golang/protobuf to 8ee79997227bf9b34611aee7946ae64735e6fd93
> Restoring /home/figure/working/go/src/github.com/golang/snappy to 7db9049039a047d955fe8c19b83c8ff5abd765c7
> Restoring /home/figure/working/go/src/github.com/go-ole/go-ole to be49f7c07711fcb603cff39e1de7c67926dc0ba7
> Restoring /home/figure/working/go/src/github.com/google/go-cmp to f94e52cad91c65a63acc1e75d4be223ea22e99bc
> Restoring /home/figure/working/go/src/github.com/gorilla/mux to 392c28fe23e1c45ddba891b0320b3b5df220beea
> Restoring /home/figure/working/go/src/github.com/hailocab/go-hostpool to e80d13ce29ede4452c43dea11e79b9bc8a15b478
> Restoring /home/figure/working/go/src/github.com/hashicorp/consul to 63d2fc68239b996096a1c55a0d4b400ea4c2583f
> Restoring /home/figure/working/go/src/github.com/influxdata/tail to a395bf99fe07c233f41fba0735fa2b13b58588ea
> Restoring /home/figure/working/go/src/github.com/influxdata/toml to 5d1d907f22ead1cd47adde17ceec5bda9cacaf8f
> Restoring /home/figure/working/go/src/github.com/influxdata/wlog to 7c63b0a71ef8300adc255344d275e10e5c3a71ec
> Restoring /home/figure/working/go/src/github.com/jackc/pgx to b84338d7d62598f75859b2b146d830b22f1b9ec8
> Restoring /home/figure/working/go/src/github.com/jmespath/go-jmespath to bd40a432e4c76585ef6b72d3fd96fb9b6dc7b68d
> Restoring /home/figure/working/go/src/github.com/kardianos/osext to c2c54e542fb797ad986b31721e1baedf214ca413
> Restoring /home/figure/working/go/src/github.com/kardianos/service to 6d3a0ee7d3425d9d835debc51a0ca1ffa28f4893
> Restoring /home/figure/working/go/src/github.com/kballard/go-shellquote to d8ec1a69a250a17bb0e419c386eac1f3711dc142
> Restoring /home/figure/working/go/src/github.com/matttproud/golang_protobuf_extensions to c12348ce28de40eed0136aa2b644d0ee0650e56c
> Restoring /home/figure/working/go/src/github.com/Microsoft/go-winio to ce2922f643c8fd76b46cadc7f404a06282678b34
> Restoring /home/figure/working/go/src/github.com/miekg/dns to 99f84ae56e75126dd77e5de4fae2ea034a468ca1
> Restoring /home/figure/working/go/src/github.com/naoina/go-stringutil to 6b638e95a32d0c1131db0e7fe83775cbea4a0d0b
> Restoring /home/figure/working/go/src/github.com/nats-io/go-nats to ea9585611a4ab58a205b9b125ebd74c389a6b898
> Restoring /home/figure/working/go/src/github.com/nats-io/nats to ea9585611a4ab58a205b9b125ebd74c389a6b898
> Restoring /home/figure/working/go/src/github.com/nats-io/nuid to 289cccf02c178dc782430d534e3c1f5b72af807f
> Restoring /home/figure/working/go/src/github.com/nsqio/go-nsq to a53d495e81424aaf7a7665a9d32a97715c40e953
> Restoring /home/figure/working/go/src/github.com/opencontainers/runc to 89ab7f2ccc1e45ddf6485eaa802c35dcf321dfc8
> Restoring /home/figure/working/go/src/github.com/opentracing-contrib/go-observer to a52f2342449246d5bcc273e65cbdcfa5f7d6c63c
> Restoring /home/figure/working/go/src/github.com/opentracing/opentracing-go to 06f47b42c792fef2796e9681353e1d908c417827
> Restoring /home/figure/working/go/src/github.com/openzipkin/zipkin-go-opentracing to 1cafbdfde94fbf2b373534764e0863aa3bd0bf7b
> Restoring /home/figure/working/go/src/github.com/pierrec/lz4 to 5c9560bfa9ace2bf86080bf40d46b34ae44604df
> Restoring /home/figure/working/go/src/github.com/pierrec/xxHash to 5a004441f897722c627870a981d02b29924215fa
> Restoring /home/figure/working/go/src/github.com/pkg/errors to 645ef00459ed84a119197bfb8d8205042c6df63d
> Restoring /home/figure/working/go/src/github.com/pmezard/go-difflib/difflib to 792786c7400a136282c1664665ae0a8db921c6c2
> Restoring /home/figure/working/go/src/github.com/prometheus/client_golang to c317fb74746eac4fc65fe3909195f4cf67c5562a
> Restoring /home/figure/working/go/src/github.com/prometheus/client_model to fa8ad6fec33561be4280a8f0514318c79d7f6cb6
> Restoring /home/figure/working/go/src/github.com/prometheus/common to dd2f054febf4a6c00f2343686efb775948a8bff4
> Restoring /home/figure/working/go/src/github.com/prometheus/procfs to 1878d9fbb537119d24b21ca07effd591627cd160
> Restoring /home/figure/working/go/src/github.com/rcrowley/go-metrics to 1f30fe9094a513ce4c700b9a54458bbb0c96996c
> Restoring /home/figure/working/go/src/github.com/samuel/go-zookeeper to 1d7be4effb13d2d908342d349d71a284a7542693
> Restoring /home/figure/working/go/src/github.com/satori/go.uuid to 5bf94b69c6b68ee1b541973bb8e1144db23a194b
> Restoring /home/figure/working/go/src/github.com/shirou/gopsutil to 9a4a9167ad3b4355dbf1c2c7a0f5f0d3fb1e9ab9
> Restoring /home/figure/working/go/src/github.com/shirou/w32 to 3c9377fc6748f222729a8270fe2775d149a249ad
> Restoring /home/figure/working/go/src/github.com/Shopify/sarama to c01858abb625b73a3af51d0798e4ad42c8147093
> Restoring /home/figure/working/go/src/github.com/Sirupsen/logrus to 61e43dc76f7ee59a82bdf3d71033dc12bea4c77d
> Restoring /home/figure/working/go/src/github.com/soniah/gosnmp to 5ad50dc75ab389f8a1c9f8a67d3a1cd85f67ed15
> Restoring /home/figure/working/go/src/github.com/StackExchange/wmi to f3e2bae1e0cb5aef83e319133eabfee30013a4a5
> Restoring /home/figure/working/go/src/github.com/streadway/amqp to 63795daa9a446c920826655f26ba31c81c860fd6
> Restoring /home/figure/working/go/src/github.com/stretchr/objx to 1a9d0bb9f541897e62256577b352fdbc1fb4fd94
> Restoring /home/figure/working/go/src/github.com/stretchr/testify to 4d4bfba8f1d1027c4fdbe371823030df51419987
> Restoring /home/figure/working/go/src/github.com/vjeantet/grok to d73e972b60935c7fec0b4ffbc904ed39ecaf7efe
> Restoring /home/figure/working/go/src/github.com/wvanbergen/kafka to bc265fedb9ff5b5c5d3c0fdcef4a819b3523d3ee
> Restoring /home/figure/working/go/src/github.com/wvanbergen/kazoo-go to 968957352185472eacb69215fa3dbfcfdbac1096
> Restoring /home/figure/working/go/src/github.com/yuin/gopher-lua to 66c871e454fcf10251c61bf8eff02d0978cae75a
> Restoring /home/figure/working/go/src/github.com/zensqlmonitor/go-mssqldb to ffe5510c6fa5e15e6d983210ab501c815b56b363
> Restoring /home/figure/working/go/src/golang.org/x/crypto to dc137beb6cce2043eb6b5f223ab8bf51c32459f4
> Restoring /home/figure/working/go/src/golang.org/x/net to f2499483f923065a842d38eb4c7f1927e6fc6e6d
> Restoring /home/figure/working/go/src/golang.org/x/sys to 739734461d1c916b6c72a63d7efda2b27edb369f
> Restoring /home/figure/working/go/src/golang.org/x/text to 506f9d5c962f284575e88337e7d9296d27e729d3
> Restoring /home/figure/working/go/src/gopkg.in/asn1-ber.v1 to 4e86f4367175e39f69d9358a5f17b4dda270378d
> Restoring /home/figure/working/go/src/gopkg.in/fatih/pool.v2 to 6e328e67893eb46323ad06f0e92cb9536babbabc
> Restoring /home/figure/working/go/src/gopkg.in/fsnotify.v1 to a8a77c9133d2d6fd8334f3260d06f60e8d80a5fb
> Restoring /home/figure/working/go/src/gopkg.in/gorethink/gorethink.v3 to 7ab832f7b65573104a555d84a27992ae9ea1f659
> Restoring /home/figure/working/go/src/gopkg.in/ldap.v2 to 8168ee085ee43257585e50c6441aadf54ecb2c9f
> Restoring /home/figure/working/go/src/gopkg.in/mgo.v2 to 3f83fa5005286a7fe593b055f0d7771a7dce4655
> Restoring /home/figure/working/go/src/gopkg.in/olivere/elastic.v5 to 3113f9b9ad37509fe5f8a0e5e91c96fdc4435e26
> Restoring /home/figure/working/go/src/gopkg.in/tomb.v1 to dd632973f1e7218eb1089048e0798ec9ae7dceb8
> Restoring /home/figure/working/go/src/gopkg.in/yaml.v2 to 4c78c975fe7c825c6d1466c42be594d1d6f3aba6



^Cmake: *** [deps] Interrupt

**Comment by arathim** [comment]
I have the same issue as above. make on telegraf master hangs. Could you please tell me how to fix it?

**Comment by danielnelson** [comment]
@arathim @xiwangren This is a different issue than what was originally reported and also this issue was closed over a year ago.  Please open a new issue when you have a new problem.

Try clearing your GOPATH and running the commands again, I think either it is unable to checkout a repository either because of network issues or because the local checkout is in a bad state.
