### ISSUE TITLE
Telegraf "master" branch doesn't compile with go 1.4.3

### ISSUE THREAD

**Issue by gena01** [influxdata/telegraf#550]
I am trying to compile telegraf master branch locally on ubuntu 14.04 and I am getting these errors using go 1.4.3:

```
# github.com/influxdb/telegraf/plugins/inputs/influxdb
plugins/inputs/influxdb/influxdb.go:97: dec.Token undefined (type *json.Decoder has no field or method Token)
plugins/inputs/influxdb/influxdb.go:99: undefined: json.Delim
plugins/inputs/influxdb/influxdb.go:106: dec.More undefined (type *json.Decoder has no field or method More)
plugins/inputs/influxdb/influxdb.go:111: dec.Token undefined (type *json.Decoder has no field or method Token)
make: *** [prepare] Error 2
```

README says 1.4+ should work?

**Comment by sparrc** [comment]
Thanks for pointing this out, I'm not going to fix this for Go 1.4.x, I'll change the README to say 1.5+
